require: rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/EmptyBlock:
  Exclude:
    - spec/**/*.rb

Lint/UselessAssignment:
  Exclude:
    - bin/console

Metrics/AbcSize:
  Exclude:
    - lib/iron_bank/associations.rb
    - lib/iron_bank/client.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - iron_bank.gemspec

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/iron_bank/error.rb

Metrics/MethodLength:
  Exclude:
    - lib/iron_bank/utils.rb
    - lib/iron_bank/associations.rb
    - lib/iron_bank/queryable.rb
    - lib/iron_bank/resources/product_rate_plan_charge_tier.rb
    - lib/iron_bank/error.rb
    - lib/iron_bank/client.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/MixinUsage:
  Exclude:
    - lib/iron_bank/resource.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/OptionalArguments:
  Exclude:
    - lib/iron_bank/local.rb
    - lib/iron_bank/queryable.rb
    - lib/iron_bank/resource.rb

Style/RegexpLiteral:
  Exclude:
    - lib/iron_bank/describe/excluded_fields.rb

Style/RescueStandardError:
  Exclude:
    - lib/iron_bank/csv.rb
