require: rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UselessAssignment:
  Exclude:
    - bin/console

Metrics/AbcSize:
  Exclude:
    - lib/iron_bank/associations.rb
    - lib/iron_bank/client.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - iron_bank.gemspec

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/iron_bank/error.rb

Metrics/MethodLength:
  Exclude:
    - lib/iron_bank/utils.rb
    - lib/iron_bank/associations.rb
    - lib/iron_bank/queryable.rb
    - lib/iron_bank/resources/product_rate_plan_charge_tier.rb
    - lib/iron_bank/error.rb
    - lib/iron_bank/client.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/MixinUsage:
  Exclude:
    - lib/iron_bank/resource.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/OptionalArguments:
  Exclude:
    - lib/iron_bank/local.rb
    - lib/iron_bank/queryable.rb
    - lib/iron_bank/resource.rb

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RegexpLiteral:
  Exclude:
    - lib/iron_bank/describe/excluded_fields.rb

Style/RescueStandardError:
  Exclude:
    - lib/iron_bank/csv.rb

Style/SlicingWithRange:
  Enabled: true
