name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Execute SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: zendesk/checkout@v2

      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: 2.7

      - uses: zendesk/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      # Only run SonarQube once per job, instead of being part of all Ruby matrix versions
      - name: SonarQube Scan Pull Request
        if: github.event_name == 'pull_request' && matrix.ruby == 2.7
        run: |
          sonar-scanner \
          -Dsonar.host.url="${{ secrets.SONARQUBE_HOST }}" \
          -Dsonar.login="${{ secrets.SONARQUBE_TOKEN }}" \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.pullrequest.base="${{ github.base_ref }}" \
          -Dsonar.pullrequest.branch="${{ github.head_ref }}" \
          -Dsonar.pullrequest.key="${{ github.event.number }}" \
          -Dsonar.pullrequest.github.repository="zendesk/${{ github.event.repository.name }}" \
          -Dsonar.scm.revision="${{ github.event.pull_request.head.sha }}"

      # Only run SonarQube once per job, instead of being part of all Ruby matrix versions
      - name: SonarQube Scan Merge to Main
        if:
          github.event_name == 'push' && github.ref == 'refs/heads/main' &&
          matrix.ruby == 2.7
        run: |
          sonar-scanner \
          -Dsonar.host.url="${{ secrets.SONARQUBE_HOST }}" \
          -Dsonar.login="${{ secrets.SONARQUBE_TOKEN }}" \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.branch.name=main
