name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Execute SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: zendesk/checkout@v2

      - name: Install SonarQube SonarScanner
        env:
          SONAR_SCANNER_VERSION: 4.5.0.2216
        run: |
          curl --location --silent \
            --output "./sonar-scanner-cli.zip" \
            "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION.zip"
          unzip "./sonar-scanner-cli.zip" -d "/opt"
          ln --force --symbolic \
            "/opt/sonar-scanner-$SONAR_SCANNER_VERSION/bin/sonar-scanner" \
            /usr/local/bin

      - name: SonarQube Scan Pull Request
        if: github.event_name == 'pull_request'
        run: |
          sonar-scanner \
          -Dsonar.host.url="${{ secrets.SONARQUBE_HOST }}" \
          -Dsonar.login="${{ secrets.SONARQUBE_TOKEN }}" \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.pullrequest.base="${{ github.base_ref }}" \
          -Dsonar.pullrequest.branch="${{ github.head_ref }}" \
          -Dsonar.pullrequest.key="${{ github.event.number }}" \
          -Dsonar.pullrequest.github.repository="zendesk/${{ github.event.repository.name }}" \
          -Dsonar.scm.revision="${{ github.event.pull_request.head.sha }}"

      - name: SonarQube Scan Merge to Main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          sonar-scanner \
          -Dsonar.host.url="${{ secrets.SONARQUBE_HOST }}" \
          -Dsonar.login="${{ secrets.SONARQUBE_TOKEN }}" \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.branch.name=main
